-- Run this once in the Supabase SQL Editor.

create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  poster_number integer not null check (poster_number between 1 and 20),
  content_score integer not null check (content_score between 1 and 7),
  presentation_score integer not null check (presentation_score between 1 and 7),
  rater_id text not null
);

-- Prevent accidental repeat voting for the same poster from the same browser.
create unique index if not exists ratings_one_per_browser_per_poster
  on public.ratings (rater_id, poster_number);

-- The Shiny app uses the Supabase service-role key stored as a Connect Cloud
-- secret, so browser clients never receive database credentials.
alter table public.ratings enable row level security;
